<?php
/** MVC
 * 1)MODEL      -> STORE THE DATE (HANDLE BUSINESS LOGIC) DATA MANAGEMENT
 * 2)VIEW       -> PHP.FILES CONTAINED HTML OR JS GET INFORMATION FROM CONTROLLER
 * 3)CONTROLLER -> TAKES UP REQUEST
 * FROM SERVER ( DEAL WITH INFO BETWEEN (VIEW) AND (MODELS)
 * DEALS WITH RESOURCES AND RESPONSES
 * 4)POUTER     -> DECIDES WHICH REQUEST OR (CONTROLLER EXECUTE) SEND TO CONTROLLER
 */